-- Logs table
create table if not exists logs (
  id bigint generated by default as identity primary key,
  level text not null default 'info',
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Mappings table (for manual and cached auto mappings)
create table if not exists mappings (
  anilist_id integer primary key,
  trakt_id integer,
  tmdb_id integer,
  imdb_id text,
  tvdb_id integer,
  type text,
  is_manual boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- System Config table (for tokens, sync status, etc.)
create table if not exists system_config (
  key text primary key,
  value text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Disable RLS for all (backend only access)
alter table logs disable row level security;
alter table mappings disable row level security;
alter table system_config disable row level security;

-- Drop old table if exists (optional, but good for cleanup)
-- drop table if exists kv_store;
